{% set name = "pyleiden" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyleiden-{{ version }}.tar.gz
  sha256: b81db474ab414ac9880ad2e0021e300366f5f826ec5091ef65755170a234c1c5

build:
  entry_points:
    - pyleiden = pyleiden.pyleiden:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - python-igraph >=0.10.3

test:
  imports:
    - pyleiden
  commands:
    - pip check
    - pyleiden --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: 'pyLeiden: a CLI tool for clustering with the Leiden algorithm'
  home: https://github.com/apcamargo/pyleiden
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apcamargo
